### ISSUE TITLE
叶分裂问题

### ISSUE THREAD

**Issue by Jie-cloud** [madsys-dev/ROART#1]
如果一个叶子(简化假设一个叶子最多4个条目)，[123000,123001,123456]，从根结点开始，经过1、下一层2、再下一层3发现为叶子数组，那如果插入123，此时叶子数组变成[123000,123001,123456,123]，如果此时又来一个1231，发生分裂，分裂的叶有[123000,123001] 和 [123456] 这两个深度相比原来加1，但是 [123] 是否会有问题，因为当前深度就是它的深度了，比较分裂前缀的时候出现level跟key长度相等，就assert了

**Comment by ErvinXie** [comment]
这个问题是所有ART树所共有的一个问题，如果中间节点不存数据，就会有这种情况发生。在实际应用场景中，需要对加入的字符串做处理保证它们两两之间不互为前缀，例如在所有字符串末尾加上一个特殊字符。
