### ISSUE TITLE
benchmark segmentation fault

### ISSUE THREAD

**Issue by GasolLY** [madsys-dev/ROART#2]
按照README.MD进行操作，想要运行benchmark。未对代码进行修改。
步骤：
（1）创建build目录
（2）cmake ..
（3）make -j
（4）./benchmark

出现Segmentation fault。

调用堆栈：
![$K_JF 5NTF$3MQWXY}`7DXA](https://user-images.githubusercontent.com/23418283/137836575-5d577e45-2620-4e01-a886-cea56aa625d4.png)

报错信息：
![JFW2OMW ZEY{VGIXV06{LF4](https://user-images.githubusercontent.com/23418283/137836756-b7cb87f5-0ba9-4e60-afa6-b4a1458a192d.png)

想请教一下：如何解决该问题，从而正常运行benchmark。（曾将config.h中的state.init_keys数目从20000000减少为20000，仍出现同样的问题

**Comment by ErvinXie** [comment]
由于数据生成器每次会生成临时文件(/tmp/random_str_data8)存储生成的字符串，如果init_keys比较少的时候生成了这个文件，在init_keys较大时会导致之前生成的字符串不够，从而使生成的串大部为空串，导致段错误。请拉取在seg fault fix这个分支的代码，并且注意在调整init_keys为更大参数之前删除tmp目录下的临时文件，即可解决此问题。

**Comment by GasolLY** [comment]
> 由于数据生成器每次会生成临时文件(/tmp/random_str_data8)存储生成的字符串，如果init_keys比较少的时候生成了这个文件，在init_keys较大时会导致之前生成的字符串不够，从而使生成的串大部为空串，导致段错误。请拉取在seg fault fix这个分支的代码，并且注意在调整init_keys为更大参数之前删除tmp目录下的临时文件，即可解决此问题。

您好，按照您的提示进行操作后，仍然出现相同的问题。
1.拉取新的fix-segfault分支代码，修改config.h与Tree.cpp中的/mnt/pmem的目录名称。
2.编译运行。
3.首次运行，提示不存在random_str_data8，并生成该文件。
4.仍然出现Segmentation Fault。

![P6 ELFK1FP%S%W(6JM@3SMU](https://user-images.githubusercontent.com/23418283/138825961-84dd634f-8856-4504-a1cd-b6778f5fc843.png)

看到之前有Issue提到叶节点分裂的问题。是否可能是LeafArray.cpp的splitAndUnlock函数中关于叶节点分裂操作的逻辑有一些小问题呢？
![)U{%757Y0GF456KB8ZT 5)P](https://user-images.githubusercontent.com/23418283/138825877-ef9b28b1-931c-44e9-92bf-aaa206807c6b.png)

**Comment by ErvinXie** [comment]
我这里是可以成功运行的
<img width="460" alt="image" src="https://user-images.githubusercontent.com/29942298/138861601-9caf0761-9efa-4063-a22d-dca7ad7192ed.png">

**Comment by GasolLY** [comment]
非常感谢同学的回复。
确实是我这边的配置和操作出现了问题，代码现在是可以成功运行的。感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "madsys-dev/ROART"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月26日(星期二) 晚上6:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [madsys-dev/ROART] benchmark segmentation fault (Issue #2)





 
我这里是可以成功运行的
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
