### ISSUE TITLE
当在LeafArray中Insert重复Key时，可能会出现Bug

### ISSUE THREAD

**Issue by GasolLY** [madsys-dev/ROART#5]
根据ART目录下，LeafArray.cppzhong中insert操作的实现，是直接寻找数组中空闲的位置进行Insert。那么当Insert相同的Key时（即Update），LeafArray中会存在新旧2个KV对（Key相同，Value不一定相同）。无法进行区分，且查询操作是直接寻找第一个Key相同的位置进行返回，可能返回的是旧值。

想请问一下，是否确实存在这样的问题？是否有解决方案呢？

```
bool LeafArray::insert(Leaf *l, bool flush) {
    auto b = bitmap.load();
    b.flip();
    auto pos = b._Find_first();
    if (pos < LeafArrayLength) {
        b.flip();
        b[pos] = true;
        bitmap.store(b);
        auto s =
            (static_cast<uintptr_t>(l->getFingerPrint()) << FingerPrintShift) |
            (reinterpret_cast<uintptr_t>(l));
        leaf[pos].store(s);
        if (flush)
            flush_data((void *)&leaf[pos], sizeof(std::atomic<uintptr_t>));

        return true;
    } else {
        return false;
    }
}
```

**Comment by MaTianmao** [comment]
你好，这个确实是实现的时候没有考虑周全。 不过前几年的一些btree的工作，比如nvtree之类的，插入数据时也都是append方式的，也会出现重复key。

**Comment by MaTianmao** [comment]
你好，这个确实是实现的时候没有考虑周全。 不过前几年的一些btree的工作，比如nvtree之类的，插入数据时也都是append方式的，也会出现重复key。
解决方案可以是，记录一个计数器count，每次插入到 array[count]的位置，然后count+1，查询的时候就从后往前查询。删除时候把bitmap对应的位置设置为0，不减少count，array[delete] = null。在节点分裂的时候再去真正删除重复的旧key。count不需要持久化，恢复的时候找到最后一个非null的指针位置去重置count。

**Comment by GasolLY** [comment]
明白了！非常感谢您的热情回复！



------------------ 原始邮件 ------------------
发件人: matianmao ***@***.***&gt;
发送时间: 2022年5月27日 10:27
收件人: madsys-dev/ROART ***@***.***&gt;
抄送: 潘许飞 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [madsys-dev/ROART] 当在LeafArray中Insert重复Key时，可能会出现Bug (Issue #5)





 
你好，这个确实是实现的时候没有考虑周全。 不过前几年的一些btree的工作，比如nvtree之类的，插入数据时也都是append方式的，也会出现重复key。
 解决方案可以是，记录一个计数器count，每次插入到 array[count]的位置，然后count+1，查询的时候就从后往前查询。删除时候把bitmap对应的位置设置为0，不减少count，array[delete] = null。在节点分裂的时候再去真正删除重复的旧key。count不需要持久化，恢复的时候找到最后一个非null的指针位置去重置count。
